// Wallet-address (lowercase, 0x-prefixed) → Swarm hash of the user's standalone
// profile page (folder containing index.html generated by the Dashboard).
// This is the v1 "fake database" — graduates to ENS contenthash lookups in v2.
//
// To populate after a Beeport upload:
//   1. From the Dashboard, click "Save & download" — produces index.html
//   2. Drop the folder containing index.html into https://beeport.ethswarm.org
//      ("Multiple files in a folder" mode)
//   3. Copy the returned manifest hash
//   4. Add an entry below: '0xyourwallet': '<manifest-hash>'
//   5. Rebuild + redeploy
export const directory: Record<string, string> = {
  // '0xd8da6bf26964af9d7eed9e03e53415d37aa96045': '<swarm-hash>',
}

export function lookupProfileHash(address: string): string | null {
  return directory[address.toLowerCase()] ?? null
}

export function getGateway(): string {
  return (
    import.meta.env.VITE_BEE_GATEWAY_URL || "https://api.gateway.ethswarm.org"
  )
}
